"""initial schema

Revision ID: a51a71ba6885
Revises: 
Create Date: 2026-06-10 20:36:18.931882+00:00
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a51a71ba6885'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brand_settings',
    sa.Column('company_name', sa.String(length=128), server_default='Seguin Morris', nullable=False),
    sa.Column('primary_color', sa.String(length=16), nullable=True),
    sa.Column('secondary_color', sa.String(length=16), nullable=True),
    sa.Column('accent_color', sa.String(length=16), nullable=True),
    sa.Column('logo_url', sa.Text(), nullable=True),
    sa.Column('designed_by_label', sa.String(length=128), server_default='Designed by CTRL Solutions', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_brand_settings'))
    )
    op.create_table('candidates',
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('current_title', sa.String(length=255), nullable=True),
    sa.Column('region', sa.String(length=128), nullable=True),
    sa.Column('candidate_type', sa.String(length=32), server_default='unknown', nullable=False),
    sa.Column('contact_email', sa.String(length=320), nullable=True),
    sa.Column('contact_phone', sa.String(length=64), nullable=True),
    sa.Column('profile_url', sa.Text(), nullable=True),
    sa.Column('fit_score', sa.Integer(), nullable=True),
    sa.Column('fit_label', sa.String(length=64), nullable=True),
    sa.Column('fit_summary', sa.Text(), nullable=True),
    sa.Column('source_confidence', sa.Integer(), nullable=True),
    sa.Column('pipeline_status', sa.Enum('NEW', 'TO_REVIEW', 'CONTACTED', 'INTERESTED', 'INTERVIEW', 'OFFER', 'HIRED', 'REJECTED', 'ARCHIVED', name='pipelinestatus', native_enum=False, length=16), server_default='new', nullable=False),
    sa.Column('consent_status', sa.String(length=32), server_default='unknown', nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_candidates'))
    )
    op.create_index(op.f('ix_candidates_contact_email'), 'candidates', ['contact_email'], unique=False)
    op.create_index(op.f('ix_candidates_full_name'), 'candidates', ['full_name'], unique=False)
    op.create_index(op.f('ix_candidates_pipeline_status'), 'candidates', ['pipeline_status'], unique=False)
    op.create_index(op.f('ix_candidates_region'), 'candidates', ['region'], unique=False)
    op.create_table('email_settings',
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('account_email', sa.String(length=320), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_email_settings'))
    )
    op.create_index(op.f('ix_email_settings_is_active'), 'email_settings', ['is_active'], unique=False)
    op.create_index(op.f('ix_email_settings_provider'), 'email_settings', ['provider'], unique=False)
    op.create_table('lead_sources',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('source_type', sa.Enum('JOB_BOARD', 'SCHOOL', 'ASSOCIATION', 'EVENT', 'SOCIAL', 'COMPANY_SITE', 'GOVERNMENT', 'MANUAL', name='sourcetype', native_enum=False, length=32), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('access_method', sa.Enum('API', 'PUBLIC_PAGE', 'BROWSER_AUTOMATION', 'MANUAL_IMPORT', 'BROWSER_CAPTURE', name='accessmethod', native_enum=False, length=32), nullable=False),
    sa.Column('allowed_to_scrape', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('last_checked_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lead_sources'))
    )
    op.create_index(op.f('ix_lead_sources_source_type'), 'lead_sources', ['source_type'], unique=False)
    op.create_table('llm_settings',
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('model_name', sa.String(length=128), nullable=False),
    sa.Column('base_url', sa.Text(), nullable=True),
    sa.Column('api_key_secret_name', sa.String(length=128), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_llm_settings'))
    )
    op.create_index(op.f('ix_llm_settings_is_active'), 'llm_settings', ['is_active'], unique=False)
    op.create_index(op.f('ix_llm_settings_provider'), 'llm_settings', ['provider'], unique=False)
    op.create_table('recruiting_events',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('date_start', sa.Date(), nullable=True),
    sa.Column('date_end', sa.Date(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=128), nullable=True),
    sa.Column('province', sa.String(length=64), nullable=True),
    sa.Column('country', sa.String(length=64), nullable=True),
    sa.Column('audience', sa.String(length=255), nullable=True),
    sa.Column('contact_name', sa.String(length=255), nullable=True),
    sa.Column('contact_email', sa.String(length=320), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('recruiting_value_score', sa.Integer(), nullable=True),
    sa.Column('recommended_action', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recruiting_events'))
    )
    op.create_table('retention_jobs',
    sa.Column('job_type', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('records_affected', sa.Integer(), server_default='0', nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('error_log', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_retention_jobs'))
    )
    op.create_index(op.f('ix_retention_jobs_job_type'), 'retention_jobs', ['job_type'], unique=False)
    op.create_index(op.f('ix_retention_jobs_status'), 'retention_jobs', ['status'], unique=False)
    op.create_table('roles',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('permissions', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles')),
    sa.UniqueConstraint('name', name=op.f('uq_roles_name'))
    )
    op.create_table('school_programs',
    sa.Column('institution_name', sa.String(length=255), nullable=False),
    sa.Column('program_name', sa.String(length=255), nullable=False),
    sa.Column('program_type', sa.String(length=32), nullable=False),
    sa.Column('city', sa.String(length=128), nullable=True),
    sa.Column('province', sa.String(length=64), nullable=True),
    sa.Column('country', sa.String(length=64), server_default='Canada', nullable=False),
    sa.Column('public_contact_name', sa.String(length=255), nullable=True),
    sa.Column('public_contact_email', sa.String(length=320), nullable=True),
    sa.Column('public_contact_phone', sa.String(length=64), nullable=True),
    sa.Column('cohort_start', sa.Date(), nullable=True),
    sa.Column('cohort_end', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_school_programs'))
    )
    op.create_index(op.f('ix_school_programs_institution_name'), 'school_programs', ['institution_name'], unique=False)
    op.create_table('source_mentions',
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('excerpt', sa.Text(), nullable=True),
    sa.Column('captured_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], name=op.f('fk_source_mentions_candidate_id_candidates'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['lead_sources.id'], name=op.f('fk_source_mentions_source_id_lead_sources'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_source_mentions'))
    )
    op.create_index(op.f('ix_source_mentions_candidate_id'), 'source_mentions', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_source_mentions_source_id'), 'source_mentions', ['source_id'], unique=False)
    op.create_table('users',
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('role_id', sa.UUID(), nullable=True),
    sa.Column('preferred_language', sa.Enum('FR', 'EN', name='language', native_enum=False, length=8), server_default='fr', nullable=False),
    sa.Column('status', sa.String(length=32), server_default='active', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_users_role_id_roles'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_role_id'), 'users', ['role_id'], unique=False)
    op.create_table('assistant_queries',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('language', sa.Enum('FR', 'EN', name='language', native_enum=False, length=8), nullable=True),
    sa.Column('sources', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_assistant_queries_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assistant_queries'))
    )
    op.create_index(op.f('ix_assistant_queries_user_id'), 'assistant_queries', ['user_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=True),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('audit_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default='now()', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_audit_logs_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_type'), 'audit_logs', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('campaigns',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('division', sa.String(length=128), nullable=False),
    sa.Column('role_type', sa.String(length=128), nullable=False),
    sa.Column('region', sa.String(length=128), nullable=False),
    sa.Column('employment_type', sa.String(length=64), nullable=True),
    sa.Column('requirements', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'PAUSED', 'CLOSED', name='campaignstatus', native_enum=False, length=16), server_default='draft', nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_campaigns_created_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_campaigns'))
    )
    op.create_index(op.f('ix_campaigns_region'), 'campaigns', ['region'], unique=False)
    op.create_index(op.f('ix_campaigns_status'), 'campaigns', ['status'], unique=False)
    op.create_table('candidate_qualifications',
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('qualification_type', sa.Enum('DEP', 'DEC', 'AEC', 'CCQ_APPRENTICE', 'CCQ_COMPANION', 'ASP_30H', 'SF1', 'SF2', 'HALOCARBURES', 'RBQ', 'DRIVER_LICENSE', 'UNKNOWN', name='qualificationtype', native_enum=False, length=32), nullable=False),
    sa.Column('qualification_status', sa.Enum('CONFIRMED', 'CLAIMED', 'INFERRED', 'MISSING', 'UNKNOWN', name='qualificationstatus', native_enum=False, length=16), nullable=False),
    sa.Column('evidence_text', sa.Text(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('verified_by_user_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], name=op.f('fk_candidate_qualifications_candidate_id_candidates'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['verified_by_user_id'], ['users.id'], name=op.f('fk_candidate_qualifications_verified_by_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_candidate_qualifications'))
    )
    op.create_index(op.f('ix_candidate_qualifications_candidate_id'), 'candidate_qualifications', ['candidate_id'], unique=False)
    op.create_table('knowledge_documents',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('language', sa.Enum('FR', 'EN', name='language', native_enum=False, length=8), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), server_default='active', nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_knowledge_documents_created_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_knowledge_documents'))
    )
    op.create_index(op.f('ix_knowledge_documents_category'), 'knowledge_documents', ['category'], unique=False)
    op.create_index(op.f('ix_knowledge_documents_status'), 'knowledge_documents', ['status'], unique=False)
    op.create_index(op.f('ix_knowledge_documents_title'), 'knowledge_documents', ['title'], unique=False)
    op.create_table('notes',
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_notes_created_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notes'))
    )
    op.create_index(op.f('ix_notes_entity_id'), 'notes', ['entity_id'], unique=False)
    op.create_index(op.f('ix_notes_entity_type'), 'notes', ['entity_type'], unique=False)
    op.create_table('agent_runs',
    sa.Column('campaign_id', sa.UUID(), nullable=True),
    sa.Column('agent_type', sa.Enum('EMPLOYMENT_SOURCE', 'SCHOOL_PIPELINE', 'EVENT_DISCOVERY', 'LEAD_ENRICHMENT', 'CANDIDATE_VETTING', 'FIT_RANKING', 'OUTREACH', 'EMAIL_SYNC', 'ASSISTANT_KNOWLEDGE', 'REPORTING', name='agenttype', native_enum=False, length=32), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', name='agentrunstatus', native_enum=False, length=16), server_default='pending', nullable=False),
    sa.Column('input_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('output_summary', sa.Text(), nullable=True),
    sa.Column('error_log', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('fk_agent_runs_campaign_id_campaigns'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_agent_runs_created_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_runs'))
    )
    op.create_index(op.f('ix_agent_runs_agent_type'), 'agent_runs', ['agent_type'], unique=False)
    op.create_index(op.f('ix_agent_runs_campaign_id'), 'agent_runs', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_agent_runs_status'), 'agent_runs', ['status'], unique=False)
    op.create_table('campaign_candidates',
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('assigned_to', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=32), server_default='active', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], name=op.f('fk_campaign_candidates_assigned_to_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('fk_campaign_candidates_campaign_id_campaigns'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], name=op.f('fk_campaign_candidates_candidate_id_candidates'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_campaign_candidates')),
    sa.UniqueConstraint('campaign_id', 'candidate_id', name='campaign_candidate')
    )
    op.create_index(op.f('ix_campaign_candidates_campaign_id'), 'campaign_candidates', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_campaign_candidates_candidate_id'), 'campaign_candidates', ['candidate_id'], unique=False)
    op.create_table('outreach_events',
    sa.Column('campaign_id', sa.UUID(), nullable=True),
    sa.Column('candidate_id', sa.UUID(), nullable=True),
    sa.Column('school_program_id', sa.UUID(), nullable=True),
    sa.Column('channel', sa.Enum('EMAIL', 'PHONE', 'SMS', 'LINKEDIN', 'IN_PERSON', name='outreachchannel', native_enum=False, length=16), nullable=False),
    sa.Column('direction', sa.Enum('OUTBOUND', 'INBOUND', name='outreachdirection', native_enum=False, length=16), nullable=False),
    sa.Column('subject', sa.Text(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('language', sa.Enum('FR', 'EN', name='language', native_enum=False, length=8), server_default='fr', nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING_APPROVAL', 'SENT', 'DELIVERED', 'OPENED', 'REPLIED', 'BOUNCED', 'FAILED', name='outreachstatus', native_enum=False, length=24), server_default='draft', nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=True),
    sa.Column('provider_message_id', sa.String(length=255), nullable=True),
    sa.Column('sent_by_user_id', sa.UUID(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('fk_outreach_events_campaign_id_campaigns'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], name=op.f('fk_outreach_events_candidate_id_candidates'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['school_program_id'], ['school_programs.id'], name=op.f('fk_outreach_events_school_program_id_school_programs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sent_by_user_id'], ['users.id'], name=op.f('fk_outreach_events_sent_by_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_outreach_events'))
    )
    op.create_index(op.f('ix_outreach_events_campaign_id'), 'outreach_events', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_outreach_events_candidate_id'), 'outreach_events', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_outreach_events_school_program_id'), 'outreach_events', ['school_program_id'], unique=False)
    op.create_index(op.f('ix_outreach_events_status'), 'outreach_events', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_outreach_events_status'), table_name='outreach_events')
    op.drop_index(op.f('ix_outreach_events_school_program_id'), table_name='outreach_events')
    op.drop_index(op.f('ix_outreach_events_candidate_id'), table_name='outreach_events')
    op.drop_index(op.f('ix_outreach_events_campaign_id'), table_name='outreach_events')
    op.drop_table('outreach_events')
    op.drop_index(op.f('ix_campaign_candidates_candidate_id'), table_name='campaign_candidates')
    op.drop_index(op.f('ix_campaign_candidates_campaign_id'), table_name='campaign_candidates')
    op.drop_table('campaign_candidates')
    op.drop_index(op.f('ix_agent_runs_status'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_campaign_id'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_agent_type'), table_name='agent_runs')
    op.drop_table('agent_runs')
    op.drop_index(op.f('ix_notes_entity_type'), table_name='notes')
    op.drop_index(op.f('ix_notes_entity_id'), table_name='notes')
    op.drop_table('notes')
    op.drop_index(op.f('ix_knowledge_documents_title'), table_name='knowledge_documents')
    op.drop_index(op.f('ix_knowledge_documents_status'), table_name='knowledge_documents')
    op.drop_index(op.f('ix_knowledge_documents_category'), table_name='knowledge_documents')
    op.drop_table('knowledge_documents')
    op.drop_index(op.f('ix_candidate_qualifications_candidate_id'), table_name='candidate_qualifications')
    op.drop_table('candidate_qualifications')
    op.drop_index(op.f('ix_campaigns_status'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_region'), table_name='campaigns')
    op.drop_table('campaigns')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_assistant_queries_user_id'), table_name='assistant_queries')
    op.drop_table('assistant_queries')
    op.drop_index(op.f('ix_users_role_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_source_mentions_source_id'), table_name='source_mentions')
    op.drop_index(op.f('ix_source_mentions_candidate_id'), table_name='source_mentions')
    op.drop_table('source_mentions')
    op.drop_index(op.f('ix_school_programs_institution_name'), table_name='school_programs')
    op.drop_table('school_programs')
    op.drop_table('roles')
    op.drop_index(op.f('ix_retention_jobs_status'), table_name='retention_jobs')
    op.drop_index(op.f('ix_retention_jobs_job_type'), table_name='retention_jobs')
    op.drop_table('retention_jobs')
    op.drop_table('recruiting_events')
    op.drop_index(op.f('ix_llm_settings_provider'), table_name='llm_settings')
    op.drop_index(op.f('ix_llm_settings_is_active'), table_name='llm_settings')
    op.drop_table('llm_settings')
    op.drop_index(op.f('ix_lead_sources_source_type'), table_name='lead_sources')
    op.drop_table('lead_sources')
    op.drop_index(op.f('ix_email_settings_provider'), table_name='email_settings')
    op.drop_index(op.f('ix_email_settings_is_active'), table_name='email_settings')
    op.drop_table('email_settings')
    op.drop_index(op.f('ix_candidates_region'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_pipeline_status'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_full_name'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_contact_email'), table_name='candidates')
    op.drop_table('candidates')
    op.drop_table('brand_settings')
    # ### end Alembic commands ###
